#
###################################
# Site wide configuration
####################################
#
title: akoksal
email:
description: NLP Research
url: https://akoksal.com
keywords: ["blog", "nlp", "computer", "vision"]
plugins:
  - jekyll-sitemap
  - jekyll-figure


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  parse_block_html: true

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Abdullatif Koksal
  avatar: 
  job: "NLP Researcher @Bogazici"
  bio: 
  email:
  disqus-shortname:
  twitter: alkksl
  facebook: #username
  google:
    plus: #username
    analytics: UA-162549108-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: akoksal
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
